name: Deploy React App
on: 
  push:
    branches:
      - "prod"
    paths-ignore:
      - 'workflows-examples/*'
jobs:
  test-my-staff:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install deps
        run: npm ci
      - name: Test App
        run: npm run test
  lint-my-code:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install deps
        run: npm ci
      - name: Lint App
        run: npm run lint
  build-my-app:
    runs-on: ubuntu-latest
    needs: [test-my-staff, lint-my-code]
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install deps
        run: npm ci
      - name: Build App
        run: npm run build
      - name: Deploy
        run: echo Deploying...
