name: Deploy React App (one job but still chained steps (deps installed only once))
on: push
jobs:
  test-lint-and-deploy-my-staff:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Test App
        run: npm run test
      - name: Lint App
        run: npm run lint
      - name: Build App
        run: npm run build
      - name: Deploy
        run: echo Deploying...
